name: Deploy Monitoring Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # GANTI INI: Dari 'ubuntu-latest' jadi 'self-hosted'
    runs-on: self-hosted 
    
    steps:
      # Kita tidak butuh 'appleboy/ssh-action' lagi karena
      # perintah di bawah ini akan dijalankan LANGSUNG di terminal Lenovo kamu.
      - name: Update and Rebuild on Lenovo Server
        run: |
          # 1. Masuk ke direktori project di server
          cd ~/project/monitoring_server
          
          # 2. Ambil perubahan kode terbaru dari GitHub
          git pull origin main
          
          # 3. Compile ulang aplikasi Go
          /usr/local/go/bin/go build -o monitoring_app .
          
          # 4. Restart service systemd
          sudo systemctl restart monitoring_server